name: Android CI/CD

on:
  push:
    tags: # This workflow runs when you push a new tag (e.g., v1.0.0)
      - 'v*' # Match tags starting with 'v'

jobs:
  build_and_release:
    runs-on: ubuntu-latest # Use a Linux runner for faster Android builds

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Action to get your repository's code

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Recommended JDK distribution
          java-version: '17'      # Use Java 17 for modern Android development

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease # Build the release APK
        env:
          # Securely pass signing credentials from GitHub Secrets
          # You'll need to set these up in your repo settings -> Secrets and variables -> Actions
          KEYSTORE_PATH: ${{ secrets.KEYSTORE_PATH }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # Only run if triggered by a tag push
        with:
          files: app/build/outputs/apk/release/app-release.apk # Path to your built APK
          name: Release ${{ github.ref_name }} # Release name will be the tag name (e.g., v1.0.0)
          draft: false # Publish immediately, set to true if you want to review first
          prerelease: false # Not a pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub's automatically provided token